### ISSUE TITLE
Python folder had been change

### ISSUE THREAD

**Issue by Superbil** [uranusjr/homebrew-pythonup#2]
I just install pythoup with `brew install --HEAD uranusjr/pythonup/pythonup`

Than got this error

> Error: No such file or directory @ dir_initialize - /usr/local/Cellar/python3

Look like this path is not existed, it should be */usr/local/Cellar/python*  on my computer.

Why not just use `which python3` to find real path for python ?

- Homebrew 1.7.0-69-g7ad999f
- macOS 10.13.6

**Comment by uranusjr** [comment]
There are a few reasons why `which python3` is a bad idea. I’ll just add a fallback to use `Cellar/python` if `python3` does not exist.

**Comment by Superbil** [comment]
Great, I can install now. But when I try to run `pythonup` got some error. 

```
ls: /usr/local/Cellar/python3: No such file or directory
/usr/local/bin/pythonup: line 6: /usr/local/Cellar/python3//bin/python3: No such file or directory
/usr/local/bin/pythonup: line 6: exec: /usr/local/Cellar/python3//bin/python3: cannot execute: No such file or directory
```
